### ISSUE TITLE
Give possibility to update a short URL to add new environments

### ISSUE THREAD

**Issue by Natim** [peterbe/whatsdeployed#28]
Sometimes you need to create the URL to put it in your contribute.json knowing that new stacks will be deployed later while you don't know their URL just yet.

Being able to create the new project and then update its list of environment would be useful.

**Comment by peterbe** [comment]
This is very unlikely to happen because if I have a short link (e.g. [5HY](https://whatsdeployed.io/s-5HY)) that represents a certain list of URLs. If *you* or someone rogue edits it without my approval now suddenly my short link URL is going to load a bunch of weird URLs for me. So you'd need authentication which is a mess. 

Another option is to make the short link based on the owner+repo (and edit the short links URLs if someone resubmits the form with the same owner+repo) but that doesn't make sense either because a repo (e.g. wordpress-org/wordpress) could be the code but two completely different companies deploy it in their own distinct infras.

**Comment by Natim** [comment]
We can use Github authentication for that and if you are an admin of the repo you can create and update the URL?

**Comment by edmorley** [comment]
Having to set up GitHub auth seems a bit like overkill for URLs needing updating occasionally.

Another way to solve this that would be both simpler and perhaps desirable for other reasons, would be to have a well known file in the repo root that describes deployed instances and the revision URLs. Then What's Deployed could just be pointed at a public GitHub repo URL, and would derive everything it needed from there (the URL would then just be https://whatsdeployed.io/?owner=mozilla&repo=treeherder). App owners would only need to modify their repo's config file rather than update URLs elsewhere.

That said, it would only work for public repos (less of an issue at Mozilla, but not for others that might use this, should that be a consideration), and is also something that I probably wouldn't need to use.
